<?php

namespace ProjectBundle\Repository;

/**
 * AuditLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditLogRepository extends \Doctrine\ORM\EntityRepository
{
}
