ProjectBundle\Entity\Type:
  type: entity
  table: null
  repositoryClass: ProjectBundle\Repository\TypeRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    cars:
      targetEntity: ProjectBundle\Entity\Car
      mappedBy: type
  lifecycleCallbacks: {  }
